### ISSUE TITLE
Error in macro TryFromMultipart in axum@0.7.1

### ISSUE THREAD

**Issue by krishnaTORQUE** [murar8/axum_typed_multipart#61] opened 2023-11-28 09:27 UTC
Error in macro TryFromMultipart in axum@0.7.1

```
4 | #[derive(TryFromMultipart)]
  |          ^^^^^^^^^^^^^^^^
  |          |
  |          expected `axum::extract::multipart::Multipart`, found `Multipart`
  |          help: change the parameter type to match the trait: `&'life0 mut axum::extract::multipart::Multipart`
  |
  = note: expected signature `fn(&'life0 mut axum::extract::multipart::Multipart) -> Pin<_>`
             found signature `fn(&'life0 mut Multipart) -> Pin<_>`
  = note: this error originates in the derive macro `TryFromMultipart` (in Nightly builds, run with -Z macro-backtrace for more info)

libunwind: malformed __unwind_info at 0x1898DECA8 bad second level page
```

**Comment by murar8** [comment] 2023-11-28 10:05
Duplicate of #60.

**Closed** 2023-11-28 10:06 UTC
